import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';
import 'package:url_launcher/url_launcher.dart';
import '../../../core/constants/config.dart';
import '../../../core/theme/theme.dart';
import '../../store/views/main_user_dashboard.dart';
import '../viewmodels/auth_viewmodel.dart';

class AccountAuthScreen extends StatefulWidget {
  const AccountAuthScreen({super.key});

  @override
  State<AccountAuthScreen> createState() => _AccountAuthScreenState();
}

class _AccountAuthScreenState extends State<AccountAuthScreen>
    with SingleTickerProviderStateMixin {
  int _activeTab = 0; // 0: Login, 1: Register

  // Login Controllers
  final _loginEmailController = TextEditingController();
  final _loginPasswordController = TextEditingController();
  bool _obscureLoginPassword = true;

  // Register Controllers (Password is generated by Admin upon approval)
  final _regNameController = TextEditingController();
  final _regEmailController = TextEditingController();
  final _regPhoneController = TextEditingController();

  bool _isSendingWhatsAppOtp = false;
  String? _regEmailError;
  String? _regPhoneError;

  late AnimationController _animController;
  late Animation<double> _fadeAnim;

  @override
  void initState() {
    super.initState();
    _animController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 700),
    );
    _fadeAnim = CurvedAnimation(parent: _animController, curve: Curves.easeOut);
    _animController.forward();
  }

  @override
  void dispose() {
    _loginEmailController.dispose();
    _loginPasswordController.dispose();
    _regNameController.dispose();
    _regEmailController.dispose();
    _regPhoneController.dispose();
    _animController.dispose();
    super.dispose();
  }

  // ─── Login Action ─────────────────────────────────────────────────────────

  // ─── Login Action ─────────────────────────────────────────────────────────

  void _submitLogin() async {
    final authViewModel = Provider.of<AuthViewModel>(context, listen: false);
    final email = _loginEmailController.text.trim();
    final password = _loginPasswordController.text;

    if (email.isEmpty || password.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('يرجى إدخال البريد الإلكتروني وكلمة المرور'),
          backgroundColor: AppTheme.errorColor,
        ),
      );
      return;
    }

    final success = await authViewModel.loginAccount(email, password);
    if (success && mounted) {
      Navigator.of(context).pushAndRemoveUntil(
        MaterialPageRoute(builder: (_) => const MainUserDashboard()),
        (route) => false,
      );
    }
  }

  // ─── Forgot Password Safe Dialog (Anti-Enumeration) ───────────────────────

  void _showForgotPasswordDialog() {
    final resetEmailController = TextEditingController(
      text: _loginEmailController.text.trim(),
    );
    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        backgroundColor: AppTheme.surfaceColorElevated,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
        title: const Row(
          children: [
            Icon(Icons.lock_reset_rounded, color: AppTheme.primaryColor),
            SizedBox(width: 8),
            Text(
              'استعادة كلمة المرور',
              style: TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.bold,
                color: AppTheme.textColor,
              ),
            ),
          ],
        ),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              'أدخل بريدك الإلكتروني لإرسال رابط إعادة تعيين كلمة المرور:',
              style: TextStyle(fontSize: 13, color: AppTheme.subtitleColor),
            ),
            const SizedBox(height: 12),
            TextField(
              controller: resetEmailController,
              keyboardType: TextInputType.emailAddress,
              style: const TextStyle(color: AppTheme.textColor),
              decoration: InputDecoration(
                hintText: 'البريد الإلكتروني',
                hintStyle: TextStyle(
                  color: AppTheme.subtitleColor.withValues(alpha: 0.5),
                ),
                prefixIcon: const Icon(
                  Icons.email_outlined,
                  color: AppTheme.primaryColor,
                ),
                filled: true,
                fillColor: AppTheme.surfaceColor,
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                  borderSide: const BorderSide(color: AppTheme.borderColor),
                ),
              ),
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx),
            child: const Text(
              'إلغاء',
              style: TextStyle(color: AppTheme.subtitleColor),
            ),
          ),
          ElevatedButton(
            style: ElevatedButton.styleFrom(
              backgroundColor: AppTheme.primaryColor,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(10),
              ),
            ),
            onPressed: () async {
              final em = resetEmailController.text.trim();
              if (em.isEmpty || !em.contains('@')) {
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(
                    content: Text('يرجى إدخال بريد إلكتروني صحيح'),
                    backgroundColor: AppTheme.errorColor,
                  ),
                );
                return;
              }
              Navigator.pop(ctx);
              final authVm = Provider.of<AuthViewModel>(context, listen: false);
              await authVm.sendPasswordResetEmail(em);
              if (mounted) {
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(
                    content: Text(
                      'إذا كان هذا البريد مسجلاً لدينا، فستصلك رسالة إعادة ضبط كلمة المرور على بريدك قريباً.',
                    ),
                    backgroundColor: AppTheme.successColor,
                    duration: Duration(seconds: 5),
                  ),
                );
              }
            },
            child: const Text(
              'إرسال الرابط',
              style: TextStyle(
                color: Colors.white,
                fontWeight: FontWeight.bold,
              ),
            ),
          ),
        ],
      ),
    );
  }

  // ─── Register Action with Strict Password & Format Validation ─────────────

  // ─── Register Action (No Password Input, Password Provisioned by Admin) ───

  void _submitRegister() async {
    final authViewModel = Provider.of<AuthViewModel>(context, listen: false);
    final name = _regNameController.text.trim();
    final email = _regEmailController.text.trim();
    final rawPhone = _regPhoneController.text.trim();

    // 1. Check empty fields
    if (name.isEmpty || email.isEmpty || rawPhone.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text(
            'يرجى ملء جميع الحقول المطلوبة (الاسم، البريد، رقم الهاتف)',
          ),
          backgroundColor: AppTheme.errorColor,
        ),
      );
      return;
    }

    // 2. Name validation: minimum 2 parts
    final nameParts = name
        .split(RegExp(r'\s+'))
        .where((p) => p.isNotEmpty)
        .toList();
    if (nameParts.length < 2) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text(
            'يرجى إدخال الاسم كاملاً (الاسم الثنائي أو الثلاثي على الأقل)',
          ),
          backgroundColor: AppTheme.errorColor,
        ),
      );
      return;
    }

    // 3. Email validation: standard RFC 5322 pattern
    final emailRegex = RegExp(
      r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$',
    );
    if (!emailRegex.hasMatch(email)) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text(
            'يرجى إدخال صيغة بريد إلكتروني صحيحة (مثال: name@example.com)',
          ),
          backgroundColor: AppTheme.errorColor,
        ),
      );
      return;
    }

    // 4. Phone validation: exactly 9 digits and starts with 77, 78, 73, or 71
    String cleanPhone = rawPhone;
    const arabicDigits = ['٠', '١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩'];
    const persianDigits = ['۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹'];
    const englishDigits = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'];
    for (int i = 0; i < 10; i++) {
      cleanPhone = cleanPhone.replaceAll(arabicDigits[i], englishDigits[i]);
      cleanPhone = cleanPhone.replaceAll(persianDigits[i], englishDigits[i]);
    }
    cleanPhone = cleanPhone.replaceAll(RegExp(r'\D'), '');
    if (cleanPhone.startsWith('00967')) {
      cleanPhone = cleanPhone.substring(5);
    } else if (cleanPhone.startsWith('967') && cleanPhone.length > 9) {
      cleanPhone = cleanPhone.substring(3);
    } else if (cleanPhone.startsWith('0')) {
      cleanPhone = cleanPhone.replaceFirst(RegExp(r'^0+'), '');
    }

    if (cleanPhone.length != 9) {
      setState(() {
        _regPhoneError = 'يجب أن يتكون رقم الهاتف من 9 أرقام';
      });
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('يجب أن يتكون رقم الهاتف من 9 أرقام (مثال: 771234567)'),
          backgroundColor: AppTheme.errorColor,
        ),
      );
      return;
    }

    const validPrefixes = ['77', '78', '73', '71'];
    if (!validPrefixes.any((prefix) => cleanPhone.startsWith(prefix))) {
      setState(() {
        _regPhoneError = 'يجب أن يبدأ رقم الهاتف بـ 77 أو 78 أو 73 أو 71';
      });
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('يجب أن يبدأ رقم الهاتف بـ 77 أو 78 أو 73 أو 71'),
          backgroundColor: AppTheme.errorColor,
        ),
      );
      return;
    }

    final phone = cleanPhone;

    // Reset previous field errors
    if (_regEmailError != null || _regPhoneError != null) {
      setState(() {
        _regEmailError = null;
        _regPhoneError = null;
      });
    }

    // Step 0: Check if phone or email is already an active user account (Zero Data Leak)
    if (mounted) setState(() => _isSendingWhatsAppOtp = true);
    try {
      final isAlreadyUser = await authViewModel.isPhoneRegisteredInUsers(phone);
      if (isAlreadyUser) {
        if (mounted) {
          setState(() {
            _isSendingWhatsAppOtp = false;
            _regPhoneError = 'رقم الهاتف مسجل لدينا بالفعل';
          });
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text(
                '⚠️ رقم الهاتف هذا مسجل لدينا بالفعل. يرجى استخدام رقم آخر أو تسجيل الدخول.',
              ),
              backgroundColor: AppTheme.errorColor,
              duration: Duration(seconds: 4),
            ),
          );
        }
        return;
      }

      final isAlreadyEmail = await authViewModel.isEmailRegisteredInUsers(
        email,
      );
      if (isAlreadyEmail) {
        if (mounted) {
          setState(() {
            _isSendingWhatsAppOtp = false;
            _regEmailError = 'البريد الإلكتروني مسجل لدينا بالفعل';
          });
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text(
                '⚠️ البريد الإلكتروني هذا مسجل لدينا بالفعل. يرجى استخدام بريد آخر أو تسجيل الدخول.',
              ),
              backgroundColor: AppTheme.errorColor,
              duration: Duration(seconds: 4),
            ),
          );
        }
        return;
      }

      // Step 0.5: Smart Recognition: Check if user already has an active registration request
      final existingReq = await authViewModel.getRegistrationRequest(phone);
      if (existingReq != null) {
        if (mounted) setState(() => _isSendingWhatsAppOtp = false);
        final reqEmail = (existingReq['email'] as String? ?? '')
            .trim()
            .toLowerCase();
        final inputEmail = email.trim().toLowerCase();

        // 🚨 ZERO DATA LEAKAGE: Check for discrepancy between entered email and request email
        if (reqEmail.isNotEmpty && reqEmail != inputEmail) {
          if (mounted) {
            setState(() {
              _regEmailError =
                  'البريد الإلكتروني غير متطابق مع بيانات الطلب المسجل';
            });
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(
                content: Text(
                  '⚠️ البريد الإلكتروني المدخل غير متطابق مع بيانات الطلب المسجل لهذا الرقم.',
                ),
                backgroundColor: AppTheme.errorColor,
                duration: Duration(seconds: 4),
              ),
            );
          }
          return;
        }

        final status = existingReq['status'] ?? '';
        final reqName = (existingReq['name'] as String? ?? '').isNotEmpty
            ? (existingReq['name'] as String)
            : name;
        final verifiedEmail = reqEmail.isNotEmpty ? reqEmail : email;

        if ((status == 'approved' || status == 'completed') && mounted) {
          _showApprovedRequestDialog(
            phone: phone,
            name: reqName,
            email: verifiedEmail,
          );
          return;
        } else if (status == 'pending' && mounted) {
          _showPendingRequestDialog(
            phone: phone,
            name: reqName,
            email: verifiedEmail,
          );
          return;
        }
      } else {
        // Phone has no request. Verify EMAIL does not belong to another active request
        final reqByEmail = await authViewModel.getRegistrationRequestByEmail(
          email,
        );
        if (reqByEmail != null) {
          if (mounted) {
            setState(() {
              _isSendingWhatsAppOtp = false;
              _regEmailError = 'البريد الإلكتروني مرتبط بطلب آخر قيد المراجعة';
            });
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(
                content: Text(
                  '⚠️ البريد الإلكتروني هذا مرتبط بطلب إنشاء حساب آخر. يرجى استخدام بريد إلكتروني آخر.',
                ),
                backgroundColor: AppTheme.errorColor,
                duration: Duration(seconds: 4),
              ),
            );
          }
          return;
        }
      }
    } catch (e) {
      debugPrint('Early phone/email check error: $e');
    }

    // Step 1: Submit Registration Request to Admin
    try {
      final reqResult = await authViewModel.submitRegistrationRequest(
        name: name,
        email: email,
        phone: phone,
      );

      if (mounted) setState(() => _isSendingWhatsAppOtp = false);

      if (reqResult['requestId'] != null && mounted) {
        _showRegistrationSuccessDialog(name: name, phone: phone, email: email);
      }
    } catch (e) {
      if (mounted) {
        setState(() => _isSendingWhatsAppOtp = false);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              authViewModel.authError ??
                  'عفواً، لا يمكن إتمام الطلب حالياً. يرجى مراجعة البيانات المدخلة.',
            ),
            backgroundColor: AppTheme.errorColor,
            duration: const Duration(seconds: 4),
          ),
        );
      }
    }
  }

  // ─── Direct WhatsApp Support Link ─────────────────────────────────────────

  Future<void> _contactAdminOnWhatsApp({String? customMessage}) async {
    final cleanPhone = AppConfig.registrationSupportNumber.replaceAll(
      RegExp(r'\D'),
      '',
    );
    final defaultMsg =
        'مرحباً إدارة شبكة تاج نت 👤\nأود الاستفسار عن طلب إنشاء الحساب.';
    final msg = Uri.encodeComponent(customMessage ?? defaultMsg);
    final directUrl = Uri.parse('whatsapp://send?phone=$cleanPhone&text=$msg');
    final webUrl = Uri.parse('https://wa.me/$cleanPhone?text=$msg');

    try {
      if (await canLaunchUrl(directUrl)) {
        await launchUrl(directUrl, mode: LaunchMode.externalApplication);
      } else {
        await launchUrl(webUrl, mode: LaunchMode.externalApplication);
      }
    } catch (_) {}
  }

  // ─── Dialog 1: Registration Success Confirmation ──────────────────────────

  void _showRegistrationSuccessDialog({
    required String name,
    required String phone,
    required String email,
  }) {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (ctx) => AlertDialog(
        backgroundColor: AppTheme.surfaceColorElevated,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(20),
          side: const BorderSide(color: AppTheme.primaryColor, width: 1.5),
        ),
        title: const Row(
          children: [
            Icon(
              Icons.mark_email_read_rounded,
              color: AppTheme.primaryColor,
              size: 28,
            ),
            SizedBox(width: 10),
            Flexible(
              child: Text(
                'تم استلام طلبك بنجاح! 🚀',
                style: TextStyle(
                  color: AppTheme.textColor,
                  fontSize: 17,
                  fontWeight: FontWeight.bold,
                ),
              ),
            ),
          ],
        ),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'أهلاً بك يا $name 👤\n\nتم استلام طلب إنشاء حسابك وهو قيد المراجعة والاعتماد لدى إدارة شبكة تاج نت حالياً.',
              style: const TextStyle(
                color: AppTheme.textColor,
                fontSize: 13.5,
                height: 1.5,
              ),
            ),
            const SizedBox(height: 12),
            Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: AppTheme.primaryColor.withValues(alpha: 0.1),
                borderRadius: BorderRadius.circular(12),
                border: Border.all(
                  color: AppTheme.primaryColor.withValues(alpha: 0.3),
                ),
              ),
              child: Row(
                children: [
                  const Icon(
                    Icons.chat_bubble_outline_rounded,
                    color: Color(0xFF25D366),
                    size: 22,
                  ),
                  const SizedBox(width: 10),
                  Expanded(
                    child: Text(
                      'فور موافقة الإدارة، سيتم إنشاء حسابك وإرسال كلمة المرور في رسالة واتساب إلى رقمك ($phone) لتسجيل الدخول مباشرة.',
                      style: const TextStyle(
                        color: AppTheme.textColor,
                        fontSize: 12.5,
                        height: 1.4,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
        actionsPadding: const EdgeInsets.symmetric(
          horizontal: 16,
          vertical: 12,
        ),
        actions: [
          ElevatedButton(
            style: ElevatedButton.styleFrom(
              backgroundColor: AppTheme.primaryColor,
              foregroundColor: Colors.black,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(12),
              ),
              padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 10),
            ),
            onPressed: () {
              Navigator.pop(ctx);
              setState(() {
                _regNameController.clear();
                _regEmailController.clear();
                _regPhoneController.clear();
                _activeTab = 0; // Switch to login tab
                _loginEmailController.text = phone; // Pre-fill with phone
              });
            },
            child: const Text(
              'الانتقال لتسجيل الدخول',
              style: TextStyle(fontWeight: FontWeight.bold),
            ),
          ),
        ],
      ),
    );
  }

  // ─── Dialog 2: Approved Request Notification ──────────────────────────────

  void _showApprovedRequestDialog({
    required String phone,
    required String name,
    required String email,
  }) {
    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        backgroundColor: AppTheme.surfaceColorElevated,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(20),
          side: const BorderSide(color: AppTheme.successColor, width: 1.5),
        ),
        title: const Row(
          children: [
            Icon(
              Icons.check_circle_rounded,
              color: AppTheme.successColor,
              size: 28,
            ),
            SizedBox(width: 10),
            Flexible(
              child: Text(
                'حسابك معتمد ومفعل مسبقاً! 🎉',
                style: TextStyle(
                  color: AppTheme.textColor,
                  fontSize: 17,
                  fontWeight: FontWeight.bold,
                ),
              ),
            ),
          ],
        ),
        content: Text(
          'تمت الموافقة على طلبك مسبقاً وإنشاء حسابك، وتم إرسال كلمة المرور إلى رقم واتساب الخاص بك ($phone).\n\nيمكنك الآن تسجيل الدخول مباشرة برقم هاتفك أو بريدك الإلكتروني مع كلمة المرور المستلمة.',
          style: const TextStyle(
            color: AppTheme.textColor,
            fontSize: 13.5,
            height: 1.5,
          ),
        ),
        actionsPadding: const EdgeInsets.symmetric(
          horizontal: 16,
          vertical: 12,
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx),
            child: const Text(
              'إلغاء',
              style: TextStyle(color: AppTheme.subtitleColor),
            ),
          ),
          ElevatedButton(
            style: ElevatedButton.styleFrom(
              backgroundColor: AppTheme.successColor,
              foregroundColor: Colors.black,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(12),
              ),
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
            ),
            onPressed: () {
              Navigator.pop(ctx);
              setState(() {
                _activeTab = 0;
                _loginEmailController.text = phone;
              });
            },
            child: const Text(
              'تسجيل الدخول الآن',
              style: TextStyle(fontWeight: FontWeight.bold),
            ),
          ),
        ],
      ),
    );
  }

  // ─── Dialog 3: Pending Request Status & Expedite ───────────────────────────

  void _showPendingRequestDialog({
    required String phone,
    required String name,
    required String email,
  }) {
    final authViewModel = Provider.of<AuthViewModel>(context, listen: false);

    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        backgroundColor: AppTheme.surfaceColorElevated,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(20),
          side: BorderSide(
            color: AppTheme.primaryColor.withValues(alpha: 0.5),
            width: 1.5,
          ),
        ),
        title: const Row(
          children: [
            Icon(
              Icons.hourglass_top_rounded,
              color: AppTheme.primaryColor,
              size: 28,
            ),
            SizedBox(width: 10),
            Flexible(
              child: Text(
                'طلبك قيد المراجعة ⏳',
                style: TextStyle(
                  color: AppTheme.textColor,
                  fontSize: 17,
                  fontWeight: FontWeight.bold,
                ),
              ),
            ),
          ],
        ),
        content: Text(
          'يوجد طلب إنشاء حساب سابق لهذا الرقم ($phone) قيد المراجعة لدى إدارة التطبيق.\n\nسيتم إنشاء الحساب وإرسال كلمة المرور إلى هاتفك عبر الواتساب فور الموافقة على الطلب.',
          style: const TextStyle(
            color: AppTheme.textColor,
            fontSize: 13.5,
            height: 1.5,
          ),
        ),
        actionsPadding: const EdgeInsets.symmetric(
          horizontal: 16,
          vertical: 12,
        ),
        actions: [
          Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              ElevatedButton.icon(
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFF25D366),
                  foregroundColor: Colors.white,
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                  padding: const EdgeInsets.symmetric(vertical: 10),
                ),
                icon: const Icon(
                  Icons.chat_rounded,
                  size: 18,
                  color: Colors.white,
                ),
                label: const Text(
                  'مراسلة الإدارة عبر واتساب للاستعجال ⚡',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                onPressed: () {
                  Navigator.pop(ctx);
                  _contactAdminOnWhatsApp(
                    customMessage:
                        'مرحباً إدارة شبكة تاج نت 👤\nقمت بتقديم طلب إنشاء حساب جديد باسم: *$name* ورقم: *$phone*، أود الاستفسار عن حالة الطلب.',
                  );
                },
              ),
              const SizedBox(height: 8),
              OutlinedButton.icon(
                style: OutlinedButton.styleFrom(
                  side: const BorderSide(color: AppTheme.errorColor),
                  foregroundColor: AppTheme.errorColor,
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                  padding: const EdgeInsets.symmetric(vertical: 10),
                ),
                icon: const Icon(Icons.delete_sweep_rounded, size: 18),
                label: const Text(
                  'إلغاء الطلب السابق والبدء من جديد',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                onPressed: () async {
                  Navigator.pop(ctx);
                  await authViewModel.cancelRegistrationRequest(phone);
                  if (mounted) {
                    ScaffoldMessenger.of(context).showSnackBar(
                      const SnackBar(
                        content: Text(
                          'تم إلغاء الطلب السابق بنجاح. يمكنك الآن تقديم طلب جديد.',
                        ),
                        backgroundColor: AppTheme.successColor,
                        duration: Duration(seconds: 4),
                      ),
                    );
                  }
                },
              ),
              const SizedBox(height: 4),
              TextButton(
                onPressed: () => Navigator.pop(ctx),
                child: const Text(
                  'إغلاق',
                  style: TextStyle(color: AppTheme.subtitleColor),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final authViewModel = Provider.of<AuthViewModel>(context);

    return Scaffold(
      body: TajNetBackground(
        child: SafeArea(
          child: FadeTransition(
            opacity: _fadeAnim,
            child: SingleChildScrollView(
              padding: const EdgeInsets.symmetric(
                horizontal: 20.0,
                vertical: 16.0,
              ),
              child: Column(
                children: [
                  const SizedBox(height: 10),

                  // Header Logo & Title
                  Container(
                    width: 104,
                    height: 104,
                    decoration: BoxDecoration(
                      shape: BoxShape.circle,
                      color: Colors.white,
                      border: Border.all(
                        color: AppTheme.primaryColor.withValues(alpha: 0.6),
                        width: 2.5,
                      ),
                      boxShadow: [
                        ...AppTheme.primaryGlow,
                        BoxShadow(
                          color: AppTheme.primaryColor.withValues(alpha: 0.25),
                          blurRadius: 18,
                          spreadRadius: 2,
                        ),
                      ],
                    ),
                    child: ClipOval(
                      child: Image.asset(
                        'assets/img/logo.jpeg',
                        fit: BoxFit.contain,
                        errorBuilder: (ctx, err, stack) => Container(
                          color: AppTheme.surfaceColorElevated,
                          child: const Icon(
                            Icons.wifi_rounded,
                            size: 40,
                            color: AppTheme.primaryColor,
                          ),
                        ),
                      ),
                    ),
                  ),

                  const SizedBox(height: 12),

                  ShaderMask(
                    shaderCallback: (bounds) =>
                        AppTheme.primaryGradient.createShader(bounds),
                    child: const Text(
                      'شبكة تاج نت',
                      style: TextStyle(
                        fontSize: 26,
                        fontWeight: FontWeight.bold,
                        color: Colors.white,
                      ),
                    ),
                  ),

                  const SizedBox(height: 4),

                  const Text(
                    'إنترنت سريع .. بلا حدود 🚀',
                    style: TextStyle(
                      fontSize: 13,
                      color: AppTheme.subtitleColor,
                    ),
                  ),

                  const SizedBox(height: 24),

                  // Tab Selector: Login vs Register
                  Container(
                    padding: const EdgeInsets.all(4),
                    decoration: BoxDecoration(
                      color: AppTheme.surfaceColor,
                      borderRadius: BorderRadius.circular(16),
                      border: Border.all(color: AppTheme.borderColor),
                    ),
                    child: Row(
                      children: [
                        Expanded(
                          child: GestureDetector(
                            onTap: () => setState(() => _activeTab = 0),
                            child: AnimatedContainer(
                              duration: const Duration(milliseconds: 250),
                              padding: const EdgeInsets.symmetric(vertical: 10),
                              decoration: BoxDecoration(
                                gradient: _activeTab == 0
                                    ? AppTheme.primaryGradient
                                    : null,
                                borderRadius: BorderRadius.circular(12),
                                boxShadow: _activeTab == 0
                                    ? AppTheme.primaryGlow
                                    : null,
                              ),
                              child: Center(
                                child: Text(
                                  'تسجيل الدخول',
                                  style: TextStyle(
                                    fontWeight: FontWeight.bold,
                                    fontSize: 14,
                                    color: _activeTab == 0
                                        ? Colors.white
                                        : AppTheme.subtitleColor,
                                  ),
                                ),
                              ),
                            ),
                          ),
                        ),
                        Expanded(
                          child: GestureDetector(
                            onTap: () => setState(() => _activeTab = 1),
                            child: AnimatedContainer(
                              duration: const Duration(milliseconds: 250),
                              padding: const EdgeInsets.symmetric(vertical: 10),
                              decoration: BoxDecoration(
                                gradient: _activeTab == 1
                                    ? AppTheme.primaryGradient
                                    : null,
                                borderRadius: BorderRadius.circular(12),
                                boxShadow: _activeTab == 1
                                    ? AppTheme.primaryGlow
                                    : null,
                              ),
                              child: Center(
                                child: Text(
                                  'إنشاء حساب جديد',
                                  style: TextStyle(
                                    fontWeight: FontWeight.bold,
                                    fontSize: 14,
                                    color: _activeTab == 1
                                        ? Colors.white
                                        : AppTheme.subtitleColor,
                                  ),
                                ),
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),

                  const SizedBox(height: 20),

                  AppCard(
                    padding: const EdgeInsets.all(20),
                    child: _activeTab == 0
                        ? _buildLoginForm(authViewModel)
                        : _buildRegisterForm(authViewModel),
                  ),

                  const SizedBox(height: 24),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }

  // ─── Form 1: Login Form ───────────────────────────────────────────────────

  Widget _buildLoginForm(AuthViewModel authViewModel) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        TextField(
          controller: _loginEmailController,
          keyboardType: TextInputType.emailAddress,
          style: const TextStyle(color: AppTheme.textColor),
          decoration: InputDecoration(
            hintText: 'رقم الهاتف أو البريد الإلكتروني',
            hintStyle: TextStyle(
              color: AppTheme.subtitleColor.withValues(alpha: 0.5),
            ),
            prefixIcon: const Icon(
              Icons.person_outline_rounded,
              color: AppTheme.primaryColor,
            ),
            filled: true,
            fillColor: AppTheme.surfaceColorElevated,
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(14),
              borderSide: const BorderSide(color: AppTheme.borderColor),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(14),
              borderSide: const BorderSide(
                color: AppTheme.primaryColor,
                width: 2,
              ),
            ),
          ),
        ),
        const SizedBox(height: 12),
        TextField(
          controller: _loginPasswordController,
          obscureText: _obscureLoginPassword,
          style: const TextStyle(color: AppTheme.textColor),
          decoration: InputDecoration(
            hintText: 'كلمة السر',
            hintStyle: TextStyle(
              color: AppTheme.subtitleColor.withValues(alpha: 0.5),
            ),
            prefixIcon: const Icon(
              Icons.lock_outline,
              color: AppTheme.primaryColor,
            ),
            suffixIcon: IconButton(
              icon: Icon(
                _obscureLoginPassword
                    ? Icons.visibility_outlined
                    : Icons.visibility_off_outlined,
                color: AppTheme.subtitleColor,
              ),
              onPressed: () => setState(
                () => _obscureLoginPassword = !_obscureLoginPassword,
              ),
            ),
            filled: true,
            fillColor: AppTheme.surfaceColorElevated,
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(14),
              borderSide: const BorderSide(color: AppTheme.borderColor),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(14),
              borderSide: const BorderSide(
                color: AppTheme.primaryColor,
                width: 2,
              ),
            ),
          ),
        ),
        const SizedBox(height: 8),
        Align(
          alignment: Alignment.centerLeft,
          child: TextButton(
            onPressed: _showForgotPasswordDialog,
            style: TextButton.styleFrom(
              padding: EdgeInsets.zero,
              minimumSize: const Size(50, 30),
              tapTargetSize: MaterialTapTargetSize.shrinkWrap,
            ),
            child: const Text(
              'نسيت كلمة المرور؟',
              style: TextStyle(
                color: AppTheme.primaryColor,
                fontSize: 13,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
        ),

        if (authViewModel.authError != null) ...[
          const SizedBox(height: 12),
          Text(
            authViewModel.authError!,
            style: const TextStyle(
              color: AppTheme.errorColor,
              fontSize: 12,
              fontWeight: FontWeight.bold,
            ),
            textAlign: TextAlign.center,
          ),
        ],

        const SizedBox(height: 16),

        TajNetButton(
          isLoading: authViewModel.isAuthLoading,
          onPressed: _submitLogin,
          child: const Text(
            'تسجيل الدخول',
            style: TextStyle(
              color: Colors.white,
              fontWeight: FontWeight.bold,
              fontSize: 15,
            ),
          ),
        ),

        if (authViewModel.canUseBiometrics &&
            authViewModel.hasSavedBiometricCredentials) ...[
          const SizedBox(height: 12),
          OutlinedButton.icon(
            style: OutlinedButton.styleFrom(
              side: const BorderSide(color: AppTheme.primaryColor),
              foregroundColor: AppTheme.primaryColor,
              padding: const EdgeInsets.symmetric(vertical: 12),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(14),
              ),
            ),
            icon: const Icon(Icons.fingerprint_rounded, size: 22),
            label: const Text(
              'الدخول السريع بالبصمة',
              style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14),
            ),
            onPressed: authViewModel.isAuthLoading
                ? null
                : () async {
                    final success = await authViewModel.loginWithBiometrics();
                    if (success && mounted) {
                      Navigator.of(context).pushAndRemoveUntil(
                        MaterialPageRoute(
                          builder: (_) => const MainUserDashboard(),
                        ),
                        (route) => false,
                      );
                    }
                  },
          ),
        ],
      ],
    );
  }

  // ─── Form 2: Register Form (Admin Provisions Password Upon Approval) ──────

  Widget _buildRegisterForm(AuthViewModel authViewModel) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        TextField(
          controller: _regNameController,
          style: const TextStyle(color: AppTheme.textColor),
          decoration: InputDecoration(
            hintText: 'الاسم الكامل (الثلاثي أو الرباعي)',
            hintStyle: TextStyle(
              color: AppTheme.subtitleColor.withValues(alpha: 0.5),
            ),
            prefixIcon: const Icon(
              Icons.person_outline,
              color: AppTheme.primaryColor,
            ),
            filled: true,
            fillColor: AppTheme.surfaceColorElevated,
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(14),
              borderSide: const BorderSide(color: AppTheme.borderColor),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(14),
              borderSide: const BorderSide(
                color: AppTheme.primaryColor,
                width: 2,
              ),
            ),
          ),
        ),
        const SizedBox(height: 10),

        TextField(
          controller: _regEmailController,
          keyboardType: TextInputType.emailAddress,
          style: const TextStyle(color: AppTheme.textColor),
          onChanged: (_) {
            if (_regEmailError != null) setState(() => _regEmailError = null);
          },
          decoration: InputDecoration(
            hintText: 'البريد الإلكتروني',
            errorText: _regEmailError,
            errorStyle: const TextStyle(
              color: AppTheme.errorColor,
              fontSize: 11.5,
              fontWeight: FontWeight.bold,
            ),
            hintStyle: TextStyle(
              color: AppTheme.subtitleColor.withValues(alpha: 0.5),
            ),
            prefixIcon: const Icon(
              Icons.email_outlined,
              color: AppTheme.primaryColor,
            ),
            filled: true,
            fillColor: AppTheme.surfaceColorElevated,
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(14),
              borderSide: const BorderSide(color: AppTheme.borderColor),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(14),
              borderSide: const BorderSide(
                color: AppTheme.primaryColor,
                width: 2,
              ),
            ),
            errorBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(14),
              borderSide: const BorderSide(color: AppTheme.errorColor),
            ),
            focusedErrorBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(14),
              borderSide: const BorderSide(
                color: AppTheme.errorColor,
                width: 2,
              ),
            ),
          ),
        ),
        const SizedBox(height: 10),

        TextField(
          controller: _regPhoneController,
          keyboardType: TextInputType.phone,
          maxLength: 9,
          inputFormatters: [YemeniPhoneInputFormatter()],
          style: const TextStyle(color: AppTheme.textColor),
          onChanged: (_) {
            if (_regPhoneError != null) setState(() => _regPhoneError = null);
          },
          decoration: InputDecoration(
            hintText: 'رقم الهاتف (9 أرقام تبدأ بـ 77، 78، 73، 71)',
            counterText: '',
            errorText: _regPhoneError,
            errorStyle: const TextStyle(
              color: AppTheme.errorColor,
              fontSize: 11.5,
              fontWeight: FontWeight.bold,
            ),
            hintStyle: TextStyle(
              color: AppTheme.subtitleColor.withValues(alpha: 0.5),
            ),
            prefixIcon: const Icon(
              Icons.phone_android_outlined,
              color: AppTheme.primaryColor,
            ),
            filled: true,
            fillColor: AppTheme.surfaceColorElevated,
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(14),
              borderSide: const BorderSide(color: AppTheme.borderColor),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(14),
              borderSide: const BorderSide(
                color: AppTheme.primaryColor,
                width: 2,
              ),
            ),
            errorBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(14),
              borderSide: const BorderSide(color: AppTheme.errorColor),
            ),
            focusedErrorBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(14),
              borderSide: const BorderSide(
                color: AppTheme.errorColor,
                width: 2,
              ),
            ),
          ),
        ),
        const SizedBox(height: 10),

        // Information notice card
        Container(
          padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
          decoration: BoxDecoration(
            color: AppTheme.primaryColor.withValues(alpha: 0.08),
            borderRadius: BorderRadius.circular(14),
            border: Border.all(
              color: AppTheme.primaryColor.withValues(alpha: 0.25),
            ),
          ),
          child: const Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Icon(
                Icons.vpn_key_outlined,
                color: AppTheme.accentGold,
                size: 20,
              ),
              SizedBox(width: 10),
              Expanded(
                child: Text(
                  'سيتم إنشاء حسابك وتوليد كلمة مرور آمنة فور موافقة إدارة الشبكة على طلبك، وستصلك في رسالة خاصة عبر الواتساب لتسجيل الدخول فوراً.',
                  style: TextStyle(
                    color: AppTheme.subtitleColor,
                    fontSize: 12.5,
                    height: 1.45,
                  ),
                ),
              ),
            ],
          ),
        ),

        if (authViewModel.authError != null) ...[
          const SizedBox(height: 12),
          Text(
            authViewModel.authError!,
            style: const TextStyle(
              color: AppTheme.errorColor,
              fontSize: 12,
              fontWeight: FontWeight.bold,
            ),
            textAlign: TextAlign.center,
          ),
        ],

        const SizedBox(height: 20),

        TajNetButton(
          isLoading: authViewModel.isAuthLoading || _isSendingWhatsAppOtp,
          onPressed: _submitRegister,
          child: const Row(
            mainAxisAlignment: MainAxisAlignment.center,
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(Icons.send_rounded, color: Colors.white, size: 18),
              SizedBox(width: 8),
              Flexible(
                child: FittedBox(
                  fit: BoxFit.scaleDown,
                  child: Text(
                    'إرسال طلب إنشاء الحساب 🚀',
                    style: TextStyle(
                      color: Colors.white,
                      fontWeight: FontWeight.bold,
                      fontSize: 15,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}

/// Formatter for Yemeni mobile numbers:
/// - Converts Arabic and Persian numerals to standard English digits
/// - Strips non-digit characters
/// - Automatically strips leading 0, 00967, or 967
/// - Capped at 9 digits
class YemeniPhoneInputFormatter extends TextInputFormatter {
  @override
  TextEditingValue formatEditUpdate(
    TextEditingValue oldValue,
    TextEditingValue newValue,
  ) {
    const arabicDigits = ['٠', '١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩'];
    const persianDigits = ['۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹'];
    const englishDigits = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'];

    String text = newValue.text;
    for (int i = 0; i < 10; i++) {
      text = text.replaceAll(arabicDigits[i], englishDigits[i]);
      text = text.replaceAll(persianDigits[i], englishDigits[i]);
    }
    text = text.replaceAll(RegExp(r'\D'), '');

    if (text.startsWith('00967')) {
      text = text.substring(5);
    } else if (text.startsWith('967') && text.length > 9) {
      text = text.substring(3);
    } else if (text.startsWith('0') && text.length > 1) {
      text = text.replaceFirst(RegExp(r'^0+'), '');
    }

    if (text.length > 9) {
      text = text.substring(0, 9);
    }

    return TextEditingValue(
      text: text,
      selection: TextSelection.collapsed(offset: text.length),
    );
  }
}
